Modify integration test
wso2/product-is pull request #12021
Opened 2021-07-01 11:56 UTC by Thisara-Welmilla

Modify the test cases as no user attributes must not be send for the 'openid' scope.

2021-07-01 12:10 UTC, emswbandara commented
let's link the integration test to the git issue @Thisara-Welmilla

2021-07-01 12:11 UTC, emswbandara commented on modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/identity/integration/test/oauth2/OAuth2RoleClaimTestCase.java
> +        Assert.assertNull(((JSONObject) idToken).get(OIDC_ROLES_CLAIM_URI), "Id token must not contain role claim");
shall we add some more details. e.g. Id token must not contain role claim which is not available in the requested scopes

2021-07-01 12:11 UTC, emswbandara commented on modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/identity/integration/test/oauth2/OAuth2RoleClaimTestCase.java
> +        Assert.assertNull(((JSONObject) idToken).get(OIDC_ROLES_CLAIM_URI), "Id token must not contain role claim");
shall we add some more details. e.g. Id token must not contain role claim which is not available in the requested scopes

2021-07-01 12:12 UTC, IsuraD commented on modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/identity/integration/test/oauth2/OAuth2RoleClaimTestCase.java
> +        Assert.assertNull(((JSONObject) idToken).get(OIDC_ROLES_CLAIM_URI), "Id token must not contain role claim");
Explain the reason. Ex. group claim is not configured for the requested scope

2021-07-01 12:14 UTC, emswbandara commented on modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/identity/integration/test/oauth2/OAuth2ServiceJWTGrantTestCase.java
>                  "Requested user claims is not returned back in self contained access token based on password "
Error message needs to be improved. 

E.g. "Requested user claims contains claims not defined in requested scopes in self contained access token based on password claim"

2021-07-01 12:15 UTC, emswbandara commented on modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/identity/integration/test/oauth2/OAuth2ServiceJWTGrantTestCase.java
> +                "User claims is not returned back with proper mappings in SP and IDP side when "
error message should be improved

2021-07-01 12:15 UTC, emswbandara commented on modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/identity/integration/test/oauth2/OAuth2ServiceJWTGrantTestCase.java
>                  "User claims are not returned back as it is when ConvertToOIDCDialect is set to false");
improve error message

2021-07-02 05:27 UTC, emswbandara approved these changes

2021-07-02 06:39 UTC, emswbandara requested changes

2021-07-02 06:39 UTC, emswbandara commented on pom.xml
> +        <identity.inbound.auth.oauth.version>6.6.32-SNAPSHOT</identity.inbound.auth.oauth.version>
update to 6.6.31

2021-07-02 08:51 UTC, emswbandara approved these changes

2021-07-02 08:51 UTC, merged