Add integration tests for Rich Authorization Requests
wso2/product-is pull request #21703
Opened 2024-11-14 04:11 UTC by VimukthiRajapaksha

### Proposed changes in this pull request

This PR introduces integration tests for the Rich Authorization Requests feature. Also, dependencies required for JSON schema validation are added.

- Add integration tests to cover Rich Authorization Requests functionality.
- Update dependencies to include JSON schema validation libraries.

### Related Issues
- https://github.com/wso2-enterprise/asgardeo-product/issues/22821

### Checklist (for reviewing)

#### General

- [ ] **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description.
- [ ] **Is the PR labeled correctly?**

#### Functionality

- [ ] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [ ] **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled.

#### Code

- [ ] **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
- [ ] **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests.
- [ ] **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/).

#### Tests

- [ ] **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components.
- [ ] **If this is a bug fix, are tests for the issue in place?**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.
- [ ] **If this is a new feature or a significant change to an existing feature?** has the manual testing spreadsheet been updated with instructions for manual testing?

#### Security

- [ ] **Confirm this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.**
- [ ] **Are all UI and API inputs run through forms or serializers?**
- [ ] **Are all external inputs validated and sanitized appropriately?**
- [ ] **Does all branching logic have a default case?**
- [ ] **Does this solution handle outliers and edge cases gracefully?**
- [ ] **Are all external communications secured and restricted to SSL?**

#### Documentation

- [ ] **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes should be documented.
- [ ] **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented.
- [ ] **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki.

2025-01-20 05:14 UTC, Thumimku commented on modules/distribution/src/assembly/bin.xml
> +                <include>io.netty:netty-handler</include>
why we need need this here

2025-01-20 09:11 UTC, Thumimku requested changes

2025-01-20 09:11 UTC, Thumimku commented on modules/distribution/src/assembly/bin.xml
> +                <include>io.netty:netty-handler</include>
If these libs required for osgi services we need to add this as orbit bundles.

2025-01-25 15:18 UTC, Thumimku commented on modules/integration/tests-integration/tests-backend/src/test/java/org/wso2/identity/integration/test/oauth2/OAuth2RichAuthorizationRequestsTestCase.java
> + * Copyright (c) 2024, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
License year

2025-01-25 17:47 UTC, Thumimku submitted a review, later dismissed
Let's bump the API-Server version also here.

2025-01-25 19:03 UTC, Thumimku approved these changes

2025-01-25 19:03 UTC, Thumimku commented
Let's merge after the builder succeed.

2025-01-25 19:04 UTC, VimukthiRajapaksha commented on modules/distribution/src/assembly/bin.xml
> +                <include>io.netty:netty-handler</include>
Removed from here and added to orbit

2025-01-26 01:05 UTC, merged